" Generated by vim-plug
" 2023-03-16T16:31:06 CET
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['MatchTagAlways'].commit = '352eb479a4ad1608e0880b79ab2357aac2cf4bed'
silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['base16-vim'].commit = '3be3cd82cd31acfcab9a41bad853d9c68d30478d'
silent! let g:plugs['coc-css'].commit = '51bf142eeacc4449d7dec0bcb1dbc06ff46034bc'
silent! let g:plugs['coc-emmet'].commit = 'ab04e2a2baad75af64781e5ca07722eceb352f8f'
silent! let g:plugs['coc-eslint'].commit = '0344fd0f1631c77d65730c465387d9c2989d2532'
silent! let g:plugs['coc-highlight'].commit = 'fb717dafef93445bdc5bb807ea0483fd505e9b8f'
silent! let g:plugs['coc-html'].commit = '532f1118a466739272e8da83cf0b5cdf8b949eb9'
silent! let g:plugs['coc-java'].commit = '4221c220437c3f54604516392cbbb04a246ce630'
silent! let g:plugs['coc-json'].commit = 'b98380d3cfa2d7d73ee0070fd20792a6e5459fe2'
silent! let g:plugs['coc-prettier'].commit = '8497a0c9229c69b0abaac27a31783892085d1572'
silent! let g:plugs['coc-rust-analyzer'].commit = '24dc182cb2f8320c0767e039b0972ae33073e7c3'
silent! let g:plugs['coc-snippets'].commit = '1b65987f4bb38712bdb245d39c3479b95f9d175f'
silent! let g:plugs['coc-tsserver'].commit = '7c8da78691bbc56cc0cca9d71eb03f325dc3ea3c'
silent! let g:plugs['coc-yaml'].commit = 'aaa247183eceb1c810b6cea6a06e7f5f6ef0de43'
silent! let g:plugs['coc-yank'].commit = '2a06ce95e9fc1b0f8630c5f94e0aef38f980310c'
silent! let g:plugs['coc.nvim'].commit = 'd0fa7acd233d76585daf9ce0b74ad1112591e271'
silent! let g:plugs['copilot.vim'].commit = '9e869d29e62e36b7eb6fb238a4ca6a6237e7d78b'
silent! let g:plugs['editorconfig-vim'].commit = 'd354117b72b3b43b75a29b8e816c0f91af10efe9'
silent! let g:plugs['emmet-vim'].commit = 'def5d57a1ae5afb1b96ebe83c4652d1c03640f4d'
silent! let g:plugs['fzf'].commit = 'f9d53303bb00225edb6e46ca1851e5cf1b55e623'
silent! let g:plugs['fzf-mru.vim'].commit = '4be854a343fade2bcccb52625640a94b550ac83d'
silent! let g:plugs['fzf.vim'].commit = '9ceac718026fd39498d95ff04fa04d3e40c465d7'
silent! let g:plugs['goyo.vim'].commit = '7f5d35a65510083ea5c2d0941797244b9963d4a9'
silent! let g:plugs['limelight.vim'].commit = '86aaec1700b27618d33d6182f44691d84d2cb6e5'
silent! let g:plugs['nerdtree'].commit = 'fc85a6f07c2cd694be93496ffad75be126240068'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['tcomment_vim'].commit = 'e77e1bf61b4f1ddc7b13c6160b7389df42aba24d'
silent! let g:plugs['vim-airline'].commit = '0ed7b8bb2ed68d65a5ba55317896680b31d315b0'
silent! let g:plugs['vim-airline-themes'].commit = 'cc5d3490c8f4c87d29d97df414941a9df8ceb390'
silent! let g:plugs['vim-fugitive'].commit = 'dd8107cabf5fe85df94d5eedcae52415e543f208'
silent! let g:plugs['vim-gitgutter'].commit = 'f19b6203191d69de955d91467a5707959572119b'
silent! let g:plugs['vim-jsdoc'].commit = '71c98ed6eacb4f1c0b9e4950ef679eda6a651cdd'
silent! let g:plugs['vim-polyglot'].commit = 'bc8a81d3592dab86334f27d1d43c080ebf680d42'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rhubarb'].commit = 'cad60fe382f3f501bbb28e113dfe8c0de6e77c75'
silent! let g:plugs['vim-search-pulse'].commit = '3ae2681332c52ed54c443e09d2ef09ae05eaa445'
silent! let g:plugs['vim-surround'].commit = 'bf3480dc9ae7bea34c78fbba4c65b4548b5b1fea'
silent! let g:plugs['vim-swap'].commit = '9358bfdc5e377aa13e7c2c2dd8699ba32b0dcf83'
silent! let g:plugs['vim-tmux-focus-events'].commit = 'b1330e04ffb95ede8e02b2f7df1f238190c67056'
silent! let g:plugs['vim-unimpaired'].commit = 'efdc6475f7ea789346716dabf9900ac04ee8604a'
silent! let g:plugs['vimproc.vim'].commit = 'f396529d7868b43d88978eb347bb203353991184'
silent! let g:plugs['vimtex'].commit = 'c16a808450da15e456d0b7055ac867886381df54'
silent! let g:plugs['vimwiki'].commit = '584f073a2809232d4793b19689da3d4d708fe4f7'

PlugStatus
if search('Invalid HEAD', 'nw')
  PlugUpdate
endif
