" Generated by vim-plug
" Sun 31 Jan 2021 07:19:59 PM CET
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['MatchTagAlways'].commit = '352eb479a4ad1608e0880b79ab2357aac2cf4bed'
silent! let g:plugs['auto-pairs'].commit = '39f06b873a8449af8ff6a3eee716d3da14d63a76'
silent! let g:plugs['base16-vim'].commit = '6191622d5806d4448fa2285047936bdcee57a098'
silent! let g:plugs['coc-css'].commit = '466552dbba8bf5de530da2e65b03b436b2be0dc5'
silent! let g:plugs['coc-emmet'].commit = '3a91ed98b83c1d54a3646f5c406d87d4c85a905a'
silent! let g:plugs['coc-eslint'].commit = 'bc6028f0a790c616dc0568b85841fb65addd81f5'
silent! let g:plugs['coc-highlight'].commit = '242d5fe13848207f90f743b4a7c0072aa2434cb9'
silent! let g:plugs['coc-html'].commit = 'bc9e176cf7220a90f5228c467a567dca5805ae3b'
silent! let g:plugs['coc-java'].commit = '64ab35d15026c138acf6c6631149692bcba4e657'
silent! let g:plugs['coc-json'].commit = '6bb083dbbd24b4bc5213d4de125e8c23a37e7422'
silent! let g:plugs['coc-prettier'].commit = 'b99ad1ba25122c6437f02e27e3d273253b4196a9'
silent! let g:plugs['coc-rust-analyzer'].commit = '87b35b5bc9cd70da2f74e38f702c82f8764d2feb'
silent! let g:plugs['coc-snippets'].commit = '2ce9caa46d640abdbd76082f62aee094396d10aa'
silent! let g:plugs['coc-tslint'].commit = 'c5303bf8118d94cc2113380e9b0a4118614a530f'
silent! let g:plugs['coc-tsserver'].commit = '17dc0c235c7be2f29211c1696edb2c82017e8e43'
silent! let g:plugs['coc-yaml'].commit = '2acb0ae832531ee12aedfa695c074d017b5cac4d'
silent! let g:plugs['coc-yank'].commit = '484a38655f9b011a0f03cad72235cf40247f4578'
silent! let g:plugs['coc.nvim'].commit = '2cece2600a433338074084e9cad3cac7ec4c3840'
silent! let g:plugs['editorconfig-vim'].commit = 'f305bc77faef4b418aee65682d7d147f64cfd5a9'
silent! let g:plugs['emmet-vim'].commit = '1f5daf6810d205844c039a4c9efa89317e62259d'
silent! let g:plugs['fzf'].commit = '7e5aa1e2a5d7cdcafd22bd4e0180316f0aa9081b'
silent! let g:plugs['fzf-mru.vim'].commit = 'e52ac60c033e61edf96d5dc0d5dc9370748fafe1'
silent! let g:plugs['fzf.vim'].commit = 'caf7754b2636eabdf1bc11d30daccc5de66951ef'
silent! let g:plugs['goyo.vim'].commit = 'a865dec7ca7616dbbd69315ad1417b84d0c411f8'
silent! let g:plugs['limelight.vim'].commit = '4412a84d7fbfd01281bf23d801e95c45c1eacc09'
silent! let g:plugs['nerdtree'].commit = '81f3eaba295b3fceb2d032db57e5eae99ae480f8'
silent! let g:plugs['nerdtree-git-plugin'].commit = '73da0283ead8fa2bbce83d219fcab3ba1e8cf0dd'
silent! let g:plugs['tcomment_vim'].commit = '8b69645999fab1933faf4fb53ae930f7c4368e79'
silent! let g:plugs['vim-airline'].commit = 'ed60e1d36912f64fdbed5640532b1067e11557ca'
silent! let g:plugs['vim-airline-themes'].commit = 'fa808d74e0aacf131337b58f01ee45fd3d3588af'
silent! let g:plugs['vim-fugitive'].commit = 'f29c9e50795cdfcc2b31b1e76ab6bd202e476298'
silent! let g:plugs['vim-gitgutter'].commit = '24cc47789557827209add5881c226243711475ce'
silent! let g:plugs['vim-jsdoc'].commit = 'fc059e80ff0b368a9188d6c16db052da6ac0951f'
silent! let g:plugs['vim-polyglot'].commit = 'cc63193ce82c1e7b9ee2ad7d0ddd14e8394211ef'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-rhubarb'].commit = '71d5c3598e0d14af3fbaf2530c061c306db5a962'
silent! let g:plugs['vim-search-pulse'].commit = '9f8f473e3813bd76ecb66e8d6182d96bda39b6df'
silent! let g:plugs['vim-surround'].commit = 'f51a26d3710629d031806305b6c8727189cd1935'
silent! let g:plugs['vim-swap'].commit = 'f363ea636f4e18b4a3382ff352d3cf2e2ac5840e'
silent! let g:plugs['vim-tmux-focus-events'].commit = '26237f9284c3853084fbf9e8303efb8fb62e0aa9'
silent! let g:plugs['vim-unimpaired'].commit = '4afbe5ebf32ad85341b4c02b0e1d8ca96a64c561'
silent! let g:plugs['vimproc.vim'].commit = '8f40d86ab938d5df8c1c9824320621ae9f0d5609'
silent! let g:plugs['vimtex'].commit = '860f6364b954cc710d3773c5299479e6099cbb9f'
silent! let g:plugs['vimwiki'].commit = '8fef79bcbd571db837312301627d3e353f3f7d78'

PlugStatus
if search('Invalid HEAD', 'nw')
  PlugUpdate
endif
