[aws]
disabled = true

[cmd_duration]
min_time = 500
show_milliseconds = true

[git_metrics]
disabled = false

[status]
disabled = false

[sudo]
disabled = false
format = "[sudo -v]($style)"

[time]
disabled = false
format = "[$time]($style) "
